# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|

  config.vm.box = "lucid32"

  config.vm.network :hostonly, "192.168.13.13"

  config.vm.provision :shell, :path => "provision.sh"

end
